### PR TITLE
Verify npm or yarn to add dependencies

### PR DESCRIPTION
**Pull request by IgorDePaula**
Verify npm or yarn to add dependencies. I, by example, prefer npm that yarn.

### CODE REVIEW

**Comment by wilcorrea** [comment]
Do you see problems in keep yarn with major priority? It is the recommended by quasar and I guess we can just alternate the precedence in the if. What do you think?

**Comment by IgorDePaula** [comment]
If quasar recomend yarn, change the order, test yarn before, npm after.

**Comment by wilcorrea** [comment]
Yep. Can you change, please?

**Comment by IgorDePaula** [comment]
Done.

**Pull request merged**
